### ISSUE TITLE
Possible/suggestion to support unix piping

### ISSUE THREAD

**Issue by thinkloop** [developit/inline-source-cli#2]
Hello, thanks for your work!

Is it possible to use this command like a standard unix command, piping in from stdin and outputting to stdout if no source/destination are provided, ex:

`cat ./build/index.html | inline-source --compress false --root ./build > ./build/newindex.html`

Best,
Baz

**Comment by developit** [comment]
@thinkloop That should actually already work. Without a second positional argument, `inline-source` outputs to `stdout` ([reference](https://github.com/developit/inline-source-cli/blob/master/src/index.js#L32-L47)).

-edit- just noticed you meant piping _to_ as well as from. I think we can make that work.

**Comment by developit** [comment]
Just released support for piping HTML into `inline-source` in version `1.1.1`. Just omit the filename or pass `"-"`. Let me know if it works for you :)

**Comment by thinkloop** [comment]
Hey that's awesome! Now I don't have to break my pipeline or hard-code paths. 

Old:

``` json
"build:html": "(pipeline) > ./build/index.html && npm run -s build:html:inlineSources" // separate sequential commands force reading from disk
"build:html:inlineSources": "inline-source --compress false --root ./build ./build/index.html ./build/index.html" // hard-coded paths
```

New: 

``` json
"build:html": "(pipeline) | npm run -s build:html:inlineSources > ./build/index.html" // clean continuous pipe
"build:html:inlineSources": "inline-source --compress false --root ./build -" // flexible and re-usable
```

I wasn't able to omit the `-` however, it said there were too few args. Not a big deal at all but would be more intuitive for future users.

Thanks!

**Comment by developit** [comment]
Ah, I may have forgotten to mark that as optional. Will fix.
